language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=Django==1.4.18 SOUTH=1
  - DJANGO=Django==1.5.12 SOUTH=1
  - DJANGO=Django==1.6.10 SOUTH=1
  - DJANGO=Django==1.7.3 SOUTH=0
  - DJANGO=https://github.com/django/django/tarball/master SOUTH=1

install:
  - pip install $DJANGO
  - pip install coverage coveralls
  - sh -c "if [ '$SOUTH' = '1' ]; then pip install South==0.8.1; fi"

script:
  - coverage run -a setup.py test
  - coverage report

matrix:
  exclude:
   - python: 2.6
     env: DJANGO=https://github.com/django/django/tarball/master SOUTH=1
   - python: 2.6
     env: DJANGO=Django==1.7.3 SOUTH=0
   - python: 3.2
     env: DJANGO=Django==1.4.18 SOUTH=1
   - python: 3.3
     env: DJANGO=Django==1.4.18 SOUTH=1
  include:
   - python: 2.7
     env: DJANGO=Django==1.5.12 SOUTH=0

after_success: coveralls
